services:

    Pdir\ContaoSeoPlugin\Controller\IndexNowTxtController:
      public: true
      arguments:
#        - '@contao.routing.page_finder'
        - '@contao.framework'

    Pdir\ContaoSeoPlugin\Controller\IndexNowController:
      public: true
